#!/usr/bin/env python3
"""scene_dump.py — dump the geometry facts the DELIVERABLE scene rows read, from a
BUILT scene.

    blender -b <scene>.blend --python pipeline/scripts/scene_dump.py -- <out.json>

WHY THIS EXISTS (DELIV-001 P1a, 2026-08-10)
--------------------------------------------
`deliverable_check.measure_scene_spec` reads a TRN-002 spec: masses with `kind` in
a primitive vocabulary and a `beauty.soft` block. Pointed at the DELIV-001 lane it
answers 0 / 0 / 0 and both MANDATORY scene rows come back PASS — a green light that
means "I could not see this spec", which is the mute this repo keeps rebuilding.

The number that makes it urgent: with those vacuous zeros, 63 of the 96 eye frames
already on disk QUALIFY as delivered-level, including frames from rounds the owner
looked at and called nowhere near done. The standard's own acceptance contract
missed it because the contract was run against ld1 and TRN-002 specs — never
against the lane the standard exists to score.

Reading the SPEC could never have worked here. The canonical room spec declares 11
objects; the scene build_room materialises from it holds 498 meshes — the tub chair,
the folded stacks, the hangers, the towels and the rug bindings are all generated by
CODE, and a spec-side check cannot see an object the spec does not know about
(placement_dump's docstring already paid for this lesson).

LAYER LAW. This file only DUMPS. Every judgement lives in `deliverable_check`,
which imports no bpy and runs under plain python (pipeline/CLAUDE.md).

THE ONE NON-OBVIOUS MEASUREMENT: `curved_clusters`
---------------------------------------------------
"Is this a curved form?" has to be answered from geometry, because the built scene
carries no `kind`. The measure is: how many clusters of face normal (15 deg) are
needed to carry 90% of the object's surface area, after dropping faces smaller than
5% of the largest face.

That last filter is not a detail — it is the whole discriminator, and the first two
versions failed their controls without it:

  * a dihedral-run metric read every WALL as a facetted curve, because
    `_bevel_edges(width_m=0.005, segments=3)` puts a 22.7 deg run across all 98
    faces of a bevelled box;
  * unfiltered cluster counting read small bevelled boxes as curved, because on an
    80 mm object the bevel rim carries a large share of the area.

A bevel rim is many faces that are each tiny beside a main face AT ANY SCALE, while
a facetted curve's side faces are all the same size as one another. Measured on 14
synthetic controls (scratchpad probe, 2026-08-10): cube 6, bevelled cube 6, bevelled
80 mm cube 6, thin panel 2, bevelled thin panel 2 / 8-gon cylinder 9, 12-gon 13,
16-gon 16, 32-gon 16, bevelled 16-gon 16, cone 15, UV sphere 95, icosphere 72. One
control disagrees and it is understood rather than tuned away: a 30 mm cube with a
5 mm 3-segment bevel reads 28, and at that ratio the object really has been rounded
into a lozenge.

SAFE ON A DELIVERABLE .blend: opens, reads the evaluated depsgraph, writes one JSON,
never saves and never mutates.
"""
import json
import math
import sys

import bpy                                              # noqa: E402

CLUSTER_TOL_DEG = 15.0      # two faces are "the same direction" within this angle
MIN_FACE_FRAC = 0.05        # drop faces below this share of the object's largest face
AREA_COVER = 0.90           # count the clusters needed to carry this much area


def curved_clusters(me, tol_deg=CLUSTER_TOL_DEG, min_face_frac=MIN_FACE_FRAC,
                    cover=AREA_COVER):
    """Clusters of face normal needed to carry `cover` of the area, small faces
    dropped first. Box -> 6 whatever the bevel does; n-gon cylinder -> ~n."""
    polys = me.polygons
    if not polys:
        return 0, 0.0
    areas = [p.area for p in polys]
    amax = max(areas)
    ct = math.cos(math.radians(tol_deg))
    clusters = []                                       # [normal, area]
    total = 0.0
    for p, a in zip(polys, areas):
        if a < min_face_frac * amax:
            continue
        n = p.normal
        total += a
        for c in clusters:
            if n[0] * c[0][0] + n[1] * c[0][1] + n[2] * c[0][2] >= ct:
                c[1] += a
                break
        else:
            clusters.append([(n[0], n[1], n[2]), a])
    if total <= 0:
        return 0, float(sum(areas))
    clusters.sort(key=lambda c: -c[1])
    acc = 0.0
    for i, c in enumerate(clusters, 1):
        acc += c[1]
        if acc >= cover * total:
            return i, float(sum(areas))
    return len(clusters), float(sum(areas))


def dump(scene=None):
    """One record per MESH object, read from the EVALUATED depsgraph so modifiers
    (solidify / subsurf / array / bevel) are in what gets measured — judging the
    cage would be judging a different object from the one that renders.

    P4b (scene-dump@2): each record now carries `item_id` (the ONE loose-item
    convention, from item_convention.py — the same pure module deliverable_check
    counts with, so the two sides cannot drift) and `in_frustum` (any bbox
    corner of the object inside the ACTIVE CAMERA's frustum). No camera in the
    scene -> the key is omitted entirely, so D7 reads NOT RUN rather than a
    confident 0 from a reader that could not see (the vacuous-zero class)."""
    import os as _os
    import sys as _sys
    _sys.path.insert(0, _os.path.dirname(_os.path.abspath(__file__)))
    import item_convention as _ic
    from bpy_extras.object_utils import world_to_camera_view as _w2cv
    from mathutils import Vector as _V
    sc = scene or bpy.context.scene
    cam = sc.camera
    dg = bpy.context.evaluated_depsgraph_get()
    out = []
    for ob in sc.objects:
        if ob.type != "MESH":
            continue
        ev = ob.evaluated_get(dg)
        me = ev.to_mesh()
        try:
            n90, area = curved_clusters(me)
            mats = [s.material.name for s in ev.material_slots if s.material]
            rec = {
                "name": ob.name,
                "hidden_render": bool(ob.hide_render),
                "polys": len(me.polygons),
                "smooth_polys": sum(1 for p in me.polygons if p.use_smooth),
                "curved_clusters": n90,
                "area_m2": round(area, 6),
                "materials": mats,
                "image_tex": sum(
                    sum(1 for nd in s.material.node_tree.nodes
                        if nd.type == "TEX_IMAGE")
                    for s in ev.material_slots
                    if s.material and s.material.use_nodes),
                "item_id": _ic.item_id(ob.name),
            }
            if cam is not None:
                rec["in_frustum"] = any(
                    0.0 <= p.x <= 1.0 and 0.0 <= p.y <= 1.0 and p.z > 0.0
                    for p in (_w2cv(sc, cam, ob.matrix_world @ _V(c))
                              for c in ob.bound_box))
                # OCCLUSION, for item-carrying objects only (the first live D7
                # count let two ensuite robe hooks through the west wall into a
                # BEDROOM styling count — a frustum cone does not stop at
                # masonry). One ray per sample point, camera -> point; the item
                # is visible if any sample's FIRST hit is the item itself or a
                # sibling part of the same item. ~70 objects, cheap.
                if rec["item_id"] and rec["in_frustum"]:
                    co = cam.matrix_world.translation
                    pts = [ob.matrix_world @ _V(c) for c in ob.bound_box]
                    ctr = sum(pts, _V((0, 0, 0))) / 8.0
                    seen = False
                    for tgt in [ctr] + pts[::2]:
                        d = tgt - co
                        if d.length < 1e-6:
                            continue
                        hit, _loc, _n, _i, hob, _m = sc.ray_cast(
                            dg, co, d.normalized(), distance=d.length + 0.05)
                        if not hit or hob is None:
                            continue
                        if (hob.name == ob.name
                                or _ic.item_id(hob.name) == rec["item_id"]):
                            seen = True
                            break
                    rec["occluded"] = not seen
            out.append(rec)
        finally:
            ev.to_mesh_clear()
    return out


# --------------------------------------------------------------------- controls --
# The calibration above is only worth what it can be re-run for. `curved_clusters`
# needs real Blender mesh data, so it cannot be pytest'd beside the pure rows the way
# placement_check is — the same position placement_dump is in. What it CAN have is
# its controls shipped with it, so nobody has to trust a number in a docstring:
#
#     blender -b --factory-startup --python pipeline/scripts/scene_dump.py -- --controls
#
# Exits 1 on any control that reads the wrong way.
CONTROLS = [
    ("cube 1m",               "flat",   dict(kind="cube", size=1.0)),
    ("cube 1m bevel 5mm x3",  "flat",   dict(kind="cube", size=1.0, bevel=(0.005, 3))),
    ("cube 80mm bevel 5mm x3", "flat",  dict(kind="cube", size=0.08, bevel=(0.005, 3))),
    ("panel 2x1x0.02",        "flat",   dict(kind="panel")),
    ("panel bevelled",        "flat",   dict(kind="panel", bevel=(0.005, 3))),
    ("cylinder 8-gon",        "curved", dict(kind="cyl", seg=8)),
    ("cylinder 12-gon",       "curved", dict(kind="cyl", seg=12)),
    ("cylinder 16-gon",       "curved", dict(kind="cyl", seg=16)),
    ("cylinder 32-gon",       "curved", dict(kind="cyl", seg=32)),
    ("cylinder 16-gon bevelled", "curved", dict(kind="cyl", seg=16, bevel=(0.005, 3))),
    ("cone 16-gon",           "curved", dict(kind="cone", seg=16)),
    ("uv sphere",             "curved", dict(kind="uvsphere")),
    ("icosphere s2",          "curved", dict(kind="icosphere")),
]
CURVED_AT = 8               # deliverable_check.CURVED_CLUSTERS_MIN — kept in step by
#                             this control set: the tightest curve here reads 9 and
#                             the loosest box reads 6.


def _control_mesh(spec):
    import bmesh
    bm = bmesh.new()
    k = spec["kind"]
    if k == "cube":
        bmesh.ops.create_cube(bm, size=spec["size"])
    elif k == "panel":
        bmesh.ops.create_cube(bm, size=1.0)
        bmesh.ops.scale(bm, vec=(2.0, 1.0, 0.02), verts=bm.verts)
    elif k == "cyl":
        bmesh.ops.create_cone(bm, segments=spec["seg"], radius1=0.3, radius2=0.3,
                              depth=0.6, cap_ends=True)
    elif k == "cone":
        bmesh.ops.create_cone(bm, segments=spec["seg"], radius1=0.3, radius2=0.0,
                              depth=0.6, cap_ends=True)
    elif k == "uvsphere":
        bmesh.ops.create_uvsphere(bm, u_segments=24, v_segments=12, radius=0.3)
    elif k == "icosphere":
        bmesh.ops.create_icosphere(bm, subdivisions=2, radius=0.3)
    if spec.get("bevel"):
        w, seg = spec["bevel"]
        bmesh.ops.bevel(bm, geom=list(bm.verts) + list(bm.edges), offset=w,
                        segments=seg, affect="EDGES", profile=0.5)
    me = bpy.data.meshes.new("ctl")
    bm.to_mesh(me)
    bm.free()
    return me


def run_controls():
    bad = 0
    print("%-28s %6s %6s  %-6s %s" % ("CONTROL", "polys", "n90", "want", "read"))
    for name, want, spec in CONTROLS:
        me = _control_mesh(spec)
        n90, _ = curved_clusters(me)
        got = "curved" if n90 >= CURVED_AT else "flat"
        bad += got != want
        print("%-28s %6d %6d  %-6s %-6s %s"
              % (name, len(me.polygons), n90, want, got,
                 "" if got == want else "<<<< MISREAD"))
        bpy.data.meshes.remove(me)
    print(f"\n{len(CONTROLS) - bad}/{len(CONTROLS)} controls read correctly")
    return 1 if bad else 0


def main():
    argv = sys.argv[sys.argv.index("--") + 1:] if "--" in sys.argv else []
    if argv and argv[0] == "--controls":
        raise SystemExit(run_controls())
    if not argv:
        raise SystemExit("scene_dump: need an output .json path (or --controls)")
    objs = dump()
    with open(argv[0], "w", encoding="utf-8") as f:
        json.dump({"blend": bpy.data.filepath, "schema": "scene-dump@2",
                   "objects": objs}, f, indent=1, ensure_ascii=False)
    print(f"scene_dump: {len(objs)} mesh objects -> {argv[0]}")


if __name__ == "__main__":
    main()
