#!/usr/bin/env python3
"""scene_dump.py — dump the geometry facts the DELIVERABLE scene rows read, from a
BUILT scene.

    blender -b <scene>.blend --python pipeline/scripts/scene_dump.py -- <out.json>

WHY THIS EXISTS (DELIV-001 P1a, 2026-08-10)
--------------------------------------------
`deliverable_check.measure_scene_spec` reads a TRN-002 spec: masses with `kind` in
a primitive vocabulary and a `beauty.soft` block. Pointed at the DELIV-001 lane it
answers 0 / 0 / 0 and both MANDATORY scene rows come back PASS — a green light that
means "I could not see this spec", which is the mute this repo keeps rebuilding.

The number that makes it urgent: with those vacuous zeros, 63 of the 96 eye frames
already on disk QUALIFY as delivered-level, including frames from rounds the owner
looked at and called nowhere near done. The standard's own acceptance contract
missed it because the contract was run against ld1 and TRN-002 specs — never
against the lane the standard exists to score.

Reading the SPEC could never have worked here. The canonical room spec declares 11
objects; the scene build_room materialises from it holds 498 meshes — the tub chair,
the folded stacks, the hangers, the towels and the rug bindings are all generated by
CODE, and a spec-side check cannot see an object the spec does not know about
(placement_dump's docstring already paid for this lesson).

LAYER LAW. This file only DUMPS. Every judgement lives in `deliverable_check`,
which imports no bpy and runs under plain python (pipeline/CLAUDE.md).

THE ONE NON-OBVIOUS MEASUREMENT: `curved_clusters`
---------------------------------------------------
"Is this a curved form?" has to be answered from geometry, because the built scene
carries no `kind`. The measure is: how many clusters of face normal (15 deg) are
needed to carry 90% of the object's surface area, after dropping faces smaller than
5% of the largest face.

That last filter is not a detail — it is the whole discriminator, and the first two
versions failed their controls without it:

  * a dihedral-run metric read every WALL as a facetted curve, because
    `_bevel_edges(width_m=0.005, segments=3)` puts a 22.7 deg run across all 98
    faces of a bevelled box;
  * unfiltered cluster counting read small bevelled boxes as curved, because on an
    80 mm object the bevel rim carries a large share of the area.

A bevel rim is many faces that are each tiny beside a main face AT ANY SCALE, while
a facetted curve's side faces are all the same size as one another. Measured on 14
synthetic controls (scratchpad probe, 2026-08-10): cube 6, bevelled cube 6, bevelled
80 mm cube 6, thin panel 2, bevelled thin panel 2 / 8-gon cylinder 9, 12-gon 13,
16-gon 16, 32-gon 16, bevelled 16-gon 16, cone 15, UV sphere 95, icosphere 72. One
control disagrees and it is understood rather than tuned away: a 30 mm cube with a
5 mm 3-segment bevel reads 28, and at that ratio the object really has been rounded
into a lozenge.

SAFE ON A DELIVERABLE .blend: opens, reads the evaluated depsgraph, writes one JSON,
never saves and never mutates.
"""
import json
import math
import sys

import bpy                                              # noqa: E402

CLUSTER_TOL_DEG = 15.0      # two faces are "the same direction" within this angle
MIN_FACE_FRAC = 0.05        # drop faces below this share of the object's largest face
AREA_COVER = 0.90           # count the clusters needed to carry this much area


def curved_clusters(me, tol_deg=CLUSTER_TOL_DEG, min_face_frac=MIN_FACE_FRAC,
                    cover=AREA_COVER):
    """Clusters of face normal needed to carry `cover` of the area, small faces
    dropped first. Box -> 6 whatever the bevel does; n-gon cylinder -> ~n."""
    polys = me.polygons
    if not polys:
        return 0, 0.0
    areas = [p.area for p in polys]
    amax = max(areas)
    ct = math.cos(math.radians(tol_deg))
    clusters = []                                       # [normal, area]
    total = 0.0
    for p, a in zip(polys, areas):
        if a < min_face_frac * amax:
            continue
        n = p.normal
        total += a
        for c in clusters:
            if n[0] * c[0][0] + n[1] * c[0][1] + n[2] * c[0][2] >= ct:
                c[1] += a
                break
        else:
            clusters.append([(n[0], n[1], n[2]), a])
    if total <= 0:
        return 0, float(sum(areas))
    clusters.sort(key=lambda c: -c[1])
    acc = 0.0
    for i, c in enumerate(clusters, 1):
        acc += c[1]
        if acc >= cover * total:
            return i, float(sum(areas))
    return len(clusters), float(sum(areas))


def dump(scene=None):
    """One record per MESH object, read from the EVALUATED depsgraph so modifiers
    (solidify / subsurf / array / bevel) are in what gets measured — judging the
    cage would be judging a different object from the one that renders.

    P4b (scene-dump@2): each record now carries `item_id` (the ONE loose-item
    convention, from item_convention.py — the same pure module deliverable_check
    counts with, so the two sides cannot drift) and `in_frustum` (any bbox
    corner of the object inside the ACTIVE CAMERA's frustum). No camera in the
    scene -> the key is omitted entirely, so D7 reads NOT RUN rather than a
    confident 0 from a reader that could not see (the vacuous-zero class)."""
    import os as _os
    import sys as _sys
    _sys.path.insert(0, _os.path.dirname(_os.path.abspath(__file__)))
    import item_convention as _ic
    from bpy_extras.object_utils import world_to_camera_view as _w2cv
    from mathutils import Vector as _V
    sc = scene or bpy.context.scene
    cam = sc.camera
    dg = bpy.context.evaluated_depsgraph_get()
    # ONE source for the pixel count, used by the per-object mm_per_px below and shipped
    # at the top of the dump by `render_res()`. Reading `sc.render.resolution_x` here and
    # applying `resolution_percentage` there would let the divisor and the STATED
    # resolution come apart by exactly that factor — which is the failure the render_res
    # key exists to prevent, committed by the key's own neighbour.
    _res_xy = render_res(sc)
    out = []
    for ob in sc.objects:
        if ob.type != "MESH":
            continue
        ev = ob.evaluated_get(dg)
        me = ev.to_mesh()
        try:
            n90, area = curved_clusters(me)
            mats = [s.material.name for s in ev.material_slots if s.material]
            rec = {
                "name": ob.name,
                "hidden_render": bool(ob.hide_render),
                "polys": len(me.polygons),
                "smooth_polys": sum(1 for p in me.polygons if p.use_smooth),
                "curved_clusters": n90,
                "area_m2": round(area, 6),
                "materials": mats,
                "image_tex": sum(
                    sum(1 for nd in s.material.node_tree.nodes
                        if nd.type == "TEX_IMAGE")
                    for s in ev.material_slots
                    if s.material and s.material.use_nodes),
                "item_id": _ic.item_id(ob.name),
            }
            # WORLD SCALE + THE MODIFIERS THAT CARE ABOUT IT (additive keys inside
            # scene-dump@2, 2026-08-29 — the schema string does not move, because
            # every consumer in this repo gates on the PRESENCE OF A KEY and none
            # compares the version: `carry_check` refuses a dump with no `aabb`,
            # `deliverable_check` reads D7 as NOT RUN with no `in_frustum`. A reader
            # written against the older dump keeps working; a reader that needs
            # these two keys must refuse when they are absent, never assume 1.0.)
            # Read off the ORIGINAL object, never the evaluated one:
            # by the time the depsgraph is done, Solidify and Bevel have already
            # spent whatever scale they were handed, so the evaluated mesh cannot
            # testify about the thing that shaped it.
            #
            # WHY THESE TWO NUMBERS AND NOT A THIRD. Solidify, Bevel, Mirror,
            # Array, Screw and Skin all evaluate their widths in the object's
            # LOCAL space, while `dimensions` and `bound_box` report WORLD size
            # and stay correct — so an object at scale 2 renders an 18 mm
            # solidify as 36 mm and every AABB-reading rung in this repo
            # (placement_check, carry_check, dim_check, the p2_exit crops) reads
            # it as perfect. The failure is invisible to all twelve keys above.
            #
            # THIS SCENE PASSES TODAY AND THAT IS THE REASON TO RECORD IT.
            # `_bake_transform_to_mesh` (build_room.py) already performs a
            # hand-rolled Ctrl+A at all three glTF import sites — but its
            # docstring argues the case entirely in TEXTURE space and never
            # mentions modifiers, so the 244 bevel widths in this scene mean
            # millimetres by a side effect nobody wrote down. An invariant that
            # holds by accident is one refactor from not holding, and until
            # these keys existed nothing in the repo could have noticed the day
            # it stopped.
            _sc = ob.matrix_world.to_scale()
            rec["scale"] = [round(v, 6) for v in _sc]
            # `show_render` is the filter, not a nicety: every other key in this
            # record comes from the EVALUATED object, which honours it. A BEVEL
            # disabled for render would otherwise report a `bevel_m` for an edge that
            # is not in the frame, and — paired with a non-unit scale — would make
            # transform_check FAIL the build over a modifier that never evaluates.
            _mods = [m for m in ob.modifiers if getattr(m, "show_render", True)]
            rec["local_space_mods"] = sorted({
                m.type for m in _mods
                if m.type in ("SOLIDIFY", "BEVEL", "MIRROR", "ARRAY", "SCREW",
                              "SKIN", "WIREFRAME")})
            # THE BEVEL'S ACTUAL WIDTH, in metres, and its segment count. A second
            # additive key with a second consumer (`edge_highlight.py`), and the
            # reason it is not folded into the line above is that the two rungs ask
            # different questions of the same modifier: transform_check asks whether
            # the number still MEANS millimetres, edge_highlight asks whether that
            # many millimetres can be SEEN from where the camera stands.
            #
            # Measured 2026-08-29 and it is why this key exists: at the eye camera's
            # 18 mm lens across 2400 px, the millwork wall sits ~3.9 m out at
            # ~3.2 mm/px, so `MILL_BEVEL_M = 0.0012` — a number chosen because a real
            # cabinet arris is nearly sharp — subtends **0.37 px** and can render no
            # highlight at all. It is right in the world and invisible in the frame,
            # and no bevel decision in this repo's history consulted the mapping
            # between the two.
            _bevs = [m for m in _mods if m.type == "BEVEL"]
            if _bevs:
                # `width` under Blender's default OFFSET mode is the distance from the
                # original edge along each adjacent face, so on a 90-degree arris the
                # chamfer face that actually catches a highlight is ~1.41x this. The
                # key is therefore a LOWER BOUND on the visible chamfer, and it is
                # recorded as the modifier's own number rather than a converted one so
                # the consumer can see which it has; `bevel_offset_type` rides along.
                rec["bevel_m"] = round(max(float(m.width) for m in _bevs), 6)
                rec["bevel_segments"] = max(int(m.segments) for m in _bevs)
                rec["bevel_offset_type"] = sorted({
                    getattr(m, "offset_type", "OFFSET") for m in _bevs})
            # HOW BIG IS ONE MILLIMETRE, HERE, IN THIS FRAME. Computed INSIDE
            # Blender against the scene's real camera and stored per object, so the
            # judging layer stays pure arithmetic and can never drift from the lens
            # that actually renders (layer law, pipeline/CLAUDE.md). Re-deriving it
            # in a pure module would mean re-implementing Blender's lens+shift+
            # sensor-fit model — an approximation of the thing we already have.
            # Two points 10 mm apart, perpendicular to the view direction, at the
            # object's own bbox centre; `None` when there is no camera, because a
            # missing camera must read as "not measured" and never as a number.
            if cam is not None:
                try:
                    _ctr = sum((ob.matrix_world @ _V(c) for c in ob.bound_box),
                               _V((0.0, 0.0, 0.0))) / 8.0
                    _vd = (_ctr - cam.matrix_world.translation)
                    _perp = _V((-_vd.y, _vd.x, 0.0))
                    if _perp.length > 1e-9 and _vd.length > 1e-9:
                        _perp = _perp.normalized() * 0.010
                        _a = _w2cv(sc, cam, _ctr)
                        _b = _w2cv(sc, cam, _ctr + _perp)
                        _dpx = math.hypot((_b.x - _a.x) * _res_xy[0],
                                          (_b.y - _a.y) * _res_xy[1])
                        if _dpx > 1e-9:
                            rec["mm_per_px"] = round(10.0 / _dpx, 6)
                except Exception:                           # noqa: BLE001
                    pass
            # World AABB of the EVALUATED object (additive @2 key). First
            # consumer: p2_exit's coincident-duplicate-shell rung — the p3r2
            # .blend probe found glTF garment sets importing the same shell
            # twice (acq0==acq10), and a rung that reads the spec would never
            # see them. 0.1 mm agreement on all six numbers = one mesh twice.
            _pts = [ev.matrix_world @ _V(c) for c in ev.bound_box]
            rec["aabb"] = [
                [round(min(p[i] for p in _pts), 6) for i in range(3)],
                [round(max(p[i] for p in _pts), 6) for i in range(3)]]
            if cam is not None:
                rec["in_frustum"] = any(
                    0.0 <= p.x <= 1.0 and 0.0 <= p.y <= 1.0 and p.z > 0.0
                    for p in (_w2cv(sc, cam, ob.matrix_world @ _V(c))
                              for c in ob.bound_box))
                # OCCLUSION, for item-carrying objects only (the first live D7
                # count let two ensuite robe hooks through the west wall into a
                # BEDROOM styling count — a frustum cone does not stop at
                # masonry). One ray per sample point, camera -> point; the item
                # is visible if any sample's FIRST hit is the item itself or a
                # sibling part of the same item. ~70 objects, cheap.
                if rec["item_id"] and rec["in_frustum"]:
                    co = cam.matrix_world.translation
                    pts = [ob.matrix_world @ _V(c) for c in ob.bound_box]
                    ctr = sum(pts, _V((0, 0, 0))) / 8.0
                    seen = False
                    for tgt in [ctr] + pts[::2]:
                        d = tgt - co
                        if d.length < 1e-6:
                            continue
                        hit, _loc, _n, _i, hob, _m = sc.ray_cast(
                            dg, co, d.normalized(), distance=d.length + 0.05)
                        if not hit or hob is None:
                            continue
                        if (hob.name == ob.name
                                or _ic.item_id(hob.name) == rec["item_id"]):
                            seen = True
                            break
                    rec["occluded"] = not seen
            out.append(rec)
        finally:
            ev.to_mesh_clear()
    return out


# --------------------------------------------------------------------- controls --
# The calibration above is only worth what it can be re-run for. `curved_clusters`
# needs real Blender mesh data, so it cannot be pytest'd beside the pure rows the way
# placement_check is — the same position placement_dump is in. What it CAN have is
# its controls shipped with it, so nobody has to trust a number in a docstring:
#
#     blender -b --factory-startup --python pipeline/scripts/scene_dump.py -- --controls
#
# Exits 1 on any control that reads the wrong way.
CONTROLS = [
    ("cube 1m",               "flat",   dict(kind="cube", size=1.0)),
    ("cube 1m bevel 5mm x3",  "flat",   dict(kind="cube", size=1.0, bevel=(0.005, 3))),
    ("cube 80mm bevel 5mm x3", "flat",  dict(kind="cube", size=0.08, bevel=(0.005, 3))),
    ("panel 2x1x0.02",        "flat",   dict(kind="panel")),
    ("panel bevelled",        "flat",   dict(kind="panel", bevel=(0.005, 3))),
    ("cylinder 8-gon",        "curved", dict(kind="cyl", seg=8)),
    ("cylinder 12-gon",       "curved", dict(kind="cyl", seg=12)),
    ("cylinder 16-gon",       "curved", dict(kind="cyl", seg=16)),
    ("cylinder 32-gon",       "curved", dict(kind="cyl", seg=32)),
    ("cylinder 16-gon bevelled", "curved", dict(kind="cyl", seg=16, bevel=(0.005, 3))),
    ("cone 16-gon",           "curved", dict(kind="cone", seg=16)),
    ("uv sphere",             "curved", dict(kind="uvsphere")),
    ("icosphere s2",          "curved", dict(kind="icosphere")),
]
CURVED_AT = 8               # deliverable_check.CURVED_CLUSTERS_MIN — kept in step by
#                             this control set: the tightest curve here reads 9 and
#                             the loosest box reads 6.


def _control_mesh(spec):
    import bmesh
    bm = bmesh.new()
    k = spec["kind"]
    if k == "cube":
        bmesh.ops.create_cube(bm, size=spec["size"])
    elif k == "panel":
        bmesh.ops.create_cube(bm, size=1.0)
        bmesh.ops.scale(bm, vec=(2.0, 1.0, 0.02), verts=bm.verts)
    elif k == "cyl":
        bmesh.ops.create_cone(bm, segments=spec["seg"], radius1=0.3, radius2=0.3,
                              depth=0.6, cap_ends=True)
    elif k == "cone":
        bmesh.ops.create_cone(bm, segments=spec["seg"], radius1=0.3, radius2=0.0,
                              depth=0.6, cap_ends=True)
    elif k == "uvsphere":
        bmesh.ops.create_uvsphere(bm, u_segments=24, v_segments=12, radius=0.3)
    elif k == "icosphere":
        bmesh.ops.create_icosphere(bm, subdivisions=2, radius=0.3)
    if spec.get("bevel"):
        w, seg = spec["bevel"]
        bmesh.ops.bevel(bm, geom=list(bm.verts) + list(bm.edges), offset=w,
                        segments=seg, affect="EDGES", profile=0.5)
    me = bpy.data.meshes.new("ctl")
    bm.to_mesh(me)
    bm.free()
    return me


def run_controls():
    bad = 0
    print("%-28s %6s %6s  %-6s %s" % ("CONTROL", "polys", "n90", "want", "read"))
    for name, want, spec in CONTROLS:
        me = _control_mesh(spec)
        n90, _ = curved_clusters(me)
        got = "curved" if n90 >= CURVED_AT else "flat"
        bad += got != want
        print("%-28s %6d %6d  %-6s %-6s %s"
              % (name, len(me.polygons), n90, want, got,
                 "" if got == want else "<<<< MISREAD"))
        bpy.data.meshes.remove(me)
    print(f"\n{len(CONTROLS) - bad}/{len(CONTROLS)} controls read correctly")
    return 1 if bad else 0


def camera_floor_poly_mm(sc=None, far_m=30.0):
    """The active camera's frustum projected onto the floor plane (z=0), as a
    convex quad in SHEET-MM (world m x1000 — the frame sheet_recon reconciles in).
    Consumer: sheet_recon's drawn-side frustum test — a DRAWN rect has no object
    to carry an `in_frustum` flag, so the camera's floor coverage must ship with
    the dump. Rays that do not descend (camera tilted up past a corner) are
    clamped at `far_m`, which keeps the quad convex and errs INCLUSIVE — a drawn
    row wrongly counted in-frustum blocks a gate, never clears one. No camera ->
    None, and sheet_recon treats unknown as blocking (vacuous-zero law)."""
    from mathutils import Vector as _V
    sc = sc or bpy.context.scene
    cam = sc.camera
    if cam is None:
        return None
    origin = cam.matrix_world.translation
    poly = []
    for corner in cam.data.view_frame(scene=sc):
        d = (cam.matrix_world @ corner) - origin
        if d.length < 1e-9:
            return None
        d = d.normalized()
        t = (-origin.z / d.z) if d.z < -1e-6 else far_m
        p = origin + d * min(t, far_m)
        poly.append([round(p.x * 1000.0, 1), round(p.y * 1000.0, 1)])
    return poly


def render_res(sc=None):
    """[x, y] pixels the scene is set to render at, resolution_percentage applied.

    IT SHIPS WITH THE DUMP BECAUSE `mm_per_px` IS MEANINGLESS WITHOUT IT, and that
    is not a theoretical worry — it bit on this key's first live run. A `_ql`
    playblast .blend carries 1200x900 while the delivered frame is 2400x1800, so
    every per-object `mm_per_px` read off a playblast is TWICE the delivered
    figure and every "how many pixels does this edge subtend" answer is HALF.
    R11's contract already says it in the pixel rung's own words: a sub-pixel
    comparison at half resolution is a different measurement, and the rung refuses
    rather than rescaling. A consumer that finds no resolution here must refuse
    too — a pixel count whose resolution is unknown is not a measurement."""
    sc = sc or bpy.context.scene
    pct = (sc.render.resolution_percentage or 100) / 100.0
    return [int(round(sc.render.resolution_x * pct)),
            int(round(sc.render.resolution_y * pct))]


def main():
    argv = sys.argv[sys.argv.index("--") + 1:] if "--" in sys.argv else []
    if argv and argv[0] == "--controls":
        raise SystemExit(run_controls())
    if not argv:
        raise SystemExit("scene_dump: need an output .json path (or --controls)")
    objs = dump()
    poly = camera_floor_poly_mm()
    out = {"blend": bpy.data.filepath, "schema": "scene-dump@2", "objects": objs,
           "render_res": render_res()}
    if poly:
        out["camera"] = {"floor_poly_mm": poly}
    with open(argv[0], "w", encoding="utf-8") as f:
        json.dump(out, f, indent=1, ensure_ascii=False)
    print(f"scene_dump: {len(objs)} mesh objects -> {argv[0]}"
          + ("" if poly else "  (no camera: floor_poly omitted)"))


if __name__ == "__main__":
    main()
